environment = "development"

[authentication]
enabled = false

[http]
port = 8080

[postgresql]
hostname = "localhost"
port = 5432
dbname = "practicelog"
username = "calvinfeng"
password = "1234"
ssl_mode="disable"
