environment = "production"

[authentication]
enabled = true

[http]
port = 8080

# Inject via Elastic Beanstalk environment
[ebdb]
hostname = "localhost"
port = 5432
dbname = "practicelog"
username = "cfeng"
password = "cfeng"
ssl_mode="disable"
